OBJS=subs.obj init.obj graphx.obj lab3d.obj setup.obj adlibemu.obj icon.obj oldlab3d.obj

default: $(OBJS)
	gcc -O3 -o ken.exe $(OBJS) `sdl-config --libs` -lSDL_image -lopengl32 -lglu32 -lwinmm -lole32 -luuid
	strip -s ken.exe

clean:
	rm -f $(OBJS)

icon.obj: ken.ico ken.rc
	windres -i ken.rc -o icon.obj

%.obj: %.c lab3d.h
	gcc -Wall -O3 `sdl-config --cflags` -o $@ -c $<


